#!/bin/sh
# dmenu_run improved
# if a command ends with "!", it is started in term.

termcmd="$TERMINAL -e"
test -s "$HOME"/.dmenurc && . "$HOME"/.dmenurc

cmd="$(dmenu_path | dmenu $@)"
case $cmd in
    *\! ) ${termcmd} "${cmd%%!}" & ;;
    * ) ${cmd} & ;;
esac
exit
